### ISSUE TITLE
App crashes in iOS

### ISSUE THREAD

**Issue by gk-tl** [bcgov/smk-tlink#152]
@NicoledeGreef When trying to zoom in to a level where street names become visible, the app continuously crashes, regardless of browser (Safari & Chrome) and browser mode (regular vs incognito). See screenshots of error message. I tried it out in dev, test, and prod. Dev and test seem slightly better than prod (but the app crashes across all three environments). 

![Pic1](https://user-images.githubusercontent.com/59627982/85311390-38298680-b46a-11ea-9f82-e68881b965be.jpg)

![Pic3](https://user-images.githubusercontent.com/59627982/85311402-3cee3a80-b46a-11ea-8ecd-4f430e22115b.jpg)

**Comment by gk-tl** [comment]
Chrome

![Pic2](https://user-images.githubusercontent.com/59627982/85311542-71fa8d00-b46a-11ea-9f22-b00dd529fabe.jpg)

**Comment by NicoledeGreef** [comment]
looks like a 404.  this is server configuration.  i will ask someone to investigate.

**Comment by NicoledeGreef** [comment]
now i cannot reproduce.  the screenshot i took on my phone lacked the BC logo too.  maybe it has been redeployed and the issue been rectified?  @gk-tl  - can you please try delivery once more?

https://translink-d.apps.gov.bc.ca/trp/

**Comment by gk-tl** [comment]
Tried again at 4:25 pm. IOS Safari.
![1A289384-F6F9-49F7-ADAB-EF7776031052](https://user-images.githubusercontent.com/59627982/85344747-6b3d3b80-b4a5-11ea-90e8-18e75e55d4a1.png)

**Comment by gk-tl** [comment]
Also, ability to pan around the map is a spotty. Instead of moving the map, the entire window pans over. This is especially problematic when dragging the map North/South as it reloads the Apop and puts user at start point (ie disclaimer screen). 

![4C44D17A-7D9F-49E2-A7A4-D668A4509257](https://user-images.githubusercontent.com/59627982/85345113-73e24180-b4a6-11ea-910a-c47f2da0ca1f.png)

**Comment by NicoledeGreef** [comment]
thanks - i got it to happen twice now.  seems intermittent on my phone in Chrome.

**Comment by NicoledeGreef** [comment]
> thanks - i got it to happen twice now. seems intermittent on my phone in Chrome.

**Comment by NicoledeGreef** [comment]
> Also, ability to pan around the map is a spotty. Instead of moving the map, the entire window pans over. This is especially problematic when dragging the map North/South as it reloads the App and puts user at start point (ie disclaimer screen).
> 

I think this is key to reproducing.  If i zoom in really carefully I don't get the error but if the entire window zooms (the tool bar too, and sort of pans) that when i get the error.

**Comment by NicoledeGreef** [comment]
re-opening as i must have closed it by accident.

**Comment by qqnluaq** [comment]
made some adjustments to CSS that hopefully stop the extraneous pinch zoom

**Comment by NicoledeGreef** [comment]
is it available at https://translink-d.apps.gov.bc.ca/trp/ ?

seems to me like you can pinch/zoom the map to a certain scale and then the rest of the app joins the zoom as well.

**Comment by gk-tl** [comment]
Panning around the map is much better, but the app still crashes when zooming in (crashed it 4 time in a row at 9:25 am).

![2020-06-24](https://user-images.githubusercontent.com/59627982/85595115-67243180-b5fd-11ea-932a-e1cfcb212e44.jpg)

**Comment by qqnluaq** [comment]
I have a bit of a mystery: on my phone (iPhone XR), this site functions as expected: https://bcgov.github.io/smk-tlink/,
but this one still has the same zooming bug: https://translink-d.apps.gov.bc.ca/trp/.
As far as I can tell the sites are serving the same code.
Investigating...

**Comment by qqnluaq** [comment]
After I figured out how to reload the page on my phone and ignore the cache, both sites behaved the same.
https://apple.stackexchange.com/questions/74797/can-i-force-a-cache-refresh-in-safari-running-on-ios

**Comment by gk-tl** [comment]
@NicoledeGreef Has this issue been resolved? Pinch/zoom and panning around the map is crashing the App for me (in dev/test).

**Comment by qqnluaq** [comment]
@gk-tl What model of iPhone are you using? Did you use my suggestion to flush the browser cache?

**Comment by NicoledeGreef** [comment]
on an iPhone 8 using Chrome, i flushed my History  (all time) and looked at https://translink-d.apps.gov.bc.ca/trp/
-if i am very careful i can pinch/zoom way in no issues; if i see the banner disappear off screen i adjust my fingers so that the banner and toolbar are back in view as normal and i can then carefully pinch zoom slowly and smoothly
- if i use fast pinch and swipe i make the "Aw snap" page happen

on iPhone * using Safari
-if i am very careful i can pinch/zoom way in no issues; if i see the banner disappear off screen i adjust my fingers so that the banner and toolbar are back in view as normal and i can then carefully pinch zoom slowly and smoothly
- if i use fast pinch and swipe the site reloads and i end up on the disclaimer modal window

**Comment by qqnluaq** [comment]
I can't reproduce any of that on my iPhone XR, in either safari or chrome.

**Comment by gk-tl** [comment]
I have an iPhone 7 Plus and a 6S Plus. I cleared my browsing data on both phones (Chrome). The App still crashes when zooming in and moving around the map.

**Comment by NicoledeGreef** [comment]
my iOS version is 13.5.1.  how about you @gk-tl  and @qqnluaq ?

**Comment by qqnluaq** [comment]
13.5.1 is the latest release, and whats on my phone.

**Comment by gk-tl** [comment]
Both my phones are on 13.5.1.

**Comment by qqnluaq** [comment]
I deployed a new build to github & dlv. I think I fixed it, please test

**Comment by NicoledeGreef** [comment]
unfortunately no change for me on iOS in https://translink-d.apps.gov.bc.ca/trp/ .  

anecdotally, the mobile testing results that have come in from DataBC show that there is no crashing on Android but it is perhaps a tad slower to render.

**Comment by gk-tl** [comment]
I'm still crashing the app in https://translink-d.apps.gov.bc.ca/trp/. 

A colleague tried it on his iPhone 8, and while the App did not crash, he indicated that after zooming in, he experienced lag making it difficult for him to move to different areas of the region.

**Comment by NicoledeGreef** [comment]
Some Testing Results:


Test   Case | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Model   (e.g. iphone 8) | iPhone   7 | iPad   Air | iPhone   6S Plus | iPhone   8 | iPhone   8 | Kindle   Fire | Samsung   Galaxy Tab E | Samsung Galaxy S8 | LG   Q6 | Model   Samsung Galaxy A8
Operating system version (e.g. iOS or android ______) | iOS 13.5.1 | iOS 13.5.1 | iOS 13.5.1 | iOS 13.5.1 | iOS 13.5.1 |   | Android | Android v.9 | Android   8.1.0 | Android   9
Browser (safari, chrome, etc.) | Safari | Safari | Chrome | Chrome | Safari | Silk | Chrome | Chrome | Chrome   browser | Browser   Samsung internet
Were you able to crash or reload the page? | Y | Y | Y | Y | Y | N |   | N | N | N
If so, was it immediate? |   |   | Y | N | N | n/a |   | n/a | n/a | n/a
General Observations | 1)	seems   to be difficult to just zoom the map and sometime the whole app/website zooms   making the header, tools and route planner form bigger     2)	zooming in and out extensively I did crash the site more than once which   forces a reload or the ‘A problem repeatedly occurred’ – I would say this was   from trying to crash it actions, but it certainly did crash | same   as above – basically the zooming the map and zooming the page seem to get   messed up then it just crashes. |   |   |   |   |   | Zooming   worked as expected.  Note: If a finger was off the map area, no zooming   happened.  Once you realize this, and stay off header or tools to begin   with, it works well. | Pinching   to zoom did not crash the app for me. However, the zooming is always about 1   second too slow responding to the zoom gesture. Panning was much more   immediately responsive. |

**Comment by gk-tl** [comment]
@NicoledeGreef thank you. The comments from iOS users are consistent with my experience. I thought part of the issue might be that we have too many layers on at the same time, but unchecking some of the cartographic layers did not appear to make much of difference (for me).

**Comment by NicoledeGreef** [comment]
@gk-tl please review:   https://translink-d.apps.gov.bc.ca/trp/

looks good to me on iphone 7 and 8.  i have asked for crowd source review again.

**Comment by gk-tl** [comment]
Tried it on chrome and safari using iPhone 6S Plus  and iphone 7 Plus. Pinch + zoom + pan works well. App no longer crashes. Hopefully, review by others will yield the same results.

Thank you!

**Comment by NicoledeGreef** [comment]
Our sample of respondents is not as large as last time however testing of the lastest build in Delivery is consistent: this fix is worthy of proceeding to Test.
